package com.cloud.base.mapper;

import com.cloud.base.entity.Advice;

import java.util.List;
import java.util.Map;

public interface AdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated
     */
    int insert(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated
     */
    Advice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated
     */
    List<Advice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Advice record);

    List<Advice> queryByKey(Map<String, Object> map);
}