package com.cloud.base.mapper;

import com.cloud.base.entity.Dc;

import java.util.List;
import java.util.Map;

public interface DcMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc
     *
     * @mbg.generated
     */
    int insert(Dc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc
     *
     * @mbg.generated
     */
    Dc selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc
     *
     * @mbg.generated
     */
    List<Dc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Dc record);

    List<Dc> queryByKey(Map<String, Object> map);
}