package com.cloud.base.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.util.Date;

public class Dc implements Serializable {
    public User user;
    public Car car;
    public String jkyj;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.xh
     *
     * @mbg.generated
     */
    private Integer xh;
    public double xhb;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.jkd
     *
     * @mbg.generated
     */
    private Integer jkd;
    public double jkdb;
    public String jkds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.rl
     *
     * @mbg.generated
     */
    private Integer rl;
    public double rlb;
    public String rls;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.dy
     *
     * @mbg.generated
     */
    private Integer dy;
    public double dyb;
    public String dys;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.nz
     *
     * @mbg.generated
     */
    private Integer nz;
    public double nzb;
    public String nzs;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.wd
     *
     * @mbg.generated
     */
    private Integer wd;
    public double wdb;
    public String wds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.zfd
     *
     * @mbg.generated
     */
    private Integer zfd;
    public double zfdb;
    public String zfds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.ctime
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.zgwd
     *
     * @mbg.generated
     */
    private String zgwd;
    public String zgwds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.zdwd
     *
     * @mbg.generated
     */
    private String zdwd;
    public String zdwds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.cdcs
     *
     * @mbg.generated
     */
    private String cdcs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc.xslc
     *
     * @mbg.generated
     */
    private String xslc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.id
     *
     * @return the value of dc.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.id
     *
     * @param id the value for dc.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.cid
     *
     * @return the value of dc.cid
     *
     * @mbg.generated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.cid
     *
     * @param cid the value for dc.cid
     *
     * @mbg.generated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.xh
     *
     * @return the value of dc.xh
     *
     * @mbg.generated
     */
    public Integer getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.xh
     *
     * @param xh the value for dc.xh
     *
     * @mbg.generated
     */
    public void setXh(Integer xh) {
        this.xh = xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.jkd
     *
     * @return the value of dc.jkd
     *
     * @mbg.generated
     */
    public Integer getJkd() {
        return jkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.jkd
     *
     * @param jkd the value for dc.jkd
     *
     * @mbg.generated
     */
    public void setJkd(Integer jkd) {
        this.jkd = jkd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.rl
     *
     * @return the value of dc.rl
     *
     * @mbg.generated
     */
    public Integer getRl() {
        return rl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.rl
     *
     * @param rl the value for dc.rl
     *
     * @mbg.generated
     */
    public void setRl(Integer rl) {
        this.rl = rl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.dy
     *
     * @return the value of dc.dy
     *
     * @mbg.generated
     */
    public Integer getDy() {
        return dy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.dy
     *
     * @param dy the value for dc.dy
     *
     * @mbg.generated
     */
    public void setDy(Integer dy) {
        this.dy = dy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.nz
     *
     * @return the value of dc.nz
     *
     * @mbg.generated
     */
    public Integer getNz() {
        return nz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.nz
     *
     * @param nz the value for dc.nz
     *
     * @mbg.generated
     */
    public void setNz(Integer nz) {
        this.nz = nz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.wd
     *
     * @return the value of dc.wd
     *
     * @mbg.generated
     */
    public Integer getWd() {
        return wd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.wd
     *
     * @param wd the value for dc.wd
     *
     * @mbg.generated
     */
    public void setWd(Integer wd) {
        this.wd = wd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.zfd
     *
     * @return the value of dc.zfd
     *
     * @mbg.generated
     */
    public Integer getZfd() {
        return zfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.zfd
     *
     * @param zfd the value for dc.zfd
     *
     * @mbg.generated
     */
    public void setZfd(Integer zfd) {
        this.zfd = zfd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.ctime
     *
     * @return the value of dc.ctime
     *
     * @mbg.generated
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.ctime
     *
     * @param ctime the value for dc.ctime
     *
     * @mbg.generated
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.uid
     *
     * @return the value of dc.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.uid
     *
     * @param uid the value for dc.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.zgwd
     *
     * @return the value of dc.zgwd
     *
     * @mbg.generated
     */
    public String getZgwd() {
        return zgwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.zgwd
     *
     * @param zgwd the value for dc.zgwd
     *
     * @mbg.generated
     */
    public void setZgwd(String zgwd) {
        this.zgwd = zgwd == null ? null : zgwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.zdwd
     *
     * @return the value of dc.zdwd
     *
     * @mbg.generated
     */
    public String getZdwd() {
        return zdwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.zdwd
     *
     * @param zdwd the value for dc.zdwd
     *
     * @mbg.generated
     */
    public void setZdwd(String zdwd) {
        this.zdwd = zdwd == null ? null : zdwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.cdcs
     *
     * @return the value of dc.cdcs
     *
     * @mbg.generated
     */
    public String getCdcs() {
        return cdcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.cdcs
     *
     * @param cdcs the value for dc.cdcs
     *
     * @mbg.generated
     */
    public void setCdcs(String cdcs) {
        this.cdcs = cdcs == null ? null : cdcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc.xslc
     *
     * @return the value of dc.xslc
     *
     * @mbg.generated
     */
    public String getXslc() {
        return xslc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc.xslc
     *
     * @param xslc the value for dc.xslc
     *
     * @mbg.generated
     */
    public void setXslc(String xslc) {
        this.xslc = xslc == null ? null : xslc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cid=").append(cid);
        sb.append(", xh=").append(xh);
        sb.append(", jkd=").append(jkd);
        sb.append(", rl=").append(rl);
        sb.append(", dy=").append(dy);
        sb.append(", nz=").append(nz);
        sb.append(", wd=").append(wd);
        sb.append(", zfd=").append(zfd);
        sb.append(", ctime=").append(ctime);
        sb.append(", uid=").append(uid);
        sb.append(", zgwd=").append(zgwd);
        sb.append(", zdwd=").append(zdwd);
        sb.append(", cdcs=").append(cdcs);
        sb.append(", xslc=").append(xslc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}